stages:
  - build
  - test
  - scan

variables:
  SAST_EXCLUDE_PATHS: "" # Порожній рядок або відсутність цього параметра означає, що будуть включені всі файли для аналізу

before_script:
  - npm install # Assuming JuiceShop is a Node.js project

build:
  stage: build
  script:
    - npm run build # Assuming there's a build script in your package.json

test:
  stage: test
  script:
    - npm test # Assuming there's a test script in your package.json

sast:
  stage: scan
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker run
        --volume "$PWD:/code"
        --workdir /code
        --env SAST_EXCLUDE_PATHS
        registry.gitlab.com/gitlab-org/security-products/analyzers/sast:latest
  artifacts:
    reports:
      sast: gl-sast-report.json
