name: Scan and Report Vulnerabilities

on:
  push:
    branches:
      - main

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Добавьте шаги для сборки и тестирования вашего кода, а также для выполнения сканирования на наличие уязвимостей
      # Например, если вы используете npm и npm audit для сканирования уязвимостей, ваш шаг может выглядеть так:
      - name: Install dependencies
        run: npm install

      - name: Run security audit
        run: npm audit --json > audit.json

      # Вместо npm audit вы можете использовать инструменты сканирования, такие как SonarQube, OWASP ZAP, или другие, в зависимости от ваших потребностей и стека технологий.
      
      # Шаг отправки результатов сканирования в DefectDojo
      - name: Send vulnerability report to DefectDojo
        env:
          DEFECT_DOJO_API_KEY: cdb534f92bdb20e27f3e08a79075e837e71aab4b
          DEFECT_DOJO_URL: http://172.26.66.248:8080/api/v2
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Token cdb534f92bdb20e27f3e08a79075e837e71aab4b" -d @audit.json "http://172.26.66.248:8080/api/v2/import-scan-results/"
